# Generated by Django 4.0.3 on 2022-03-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_customuser_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role_id',
            field=models.CharField(choices=[('0', 'Patient'), ('1', 'Doctor')], default='0', max_length=1),
        ),
    ]
